
networks:
  ra-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  rabbitmq_data:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: Prometheus-RA
    volumes:
      - ./src/main/resources/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - ra-network
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: Grafana-RA
    ports:
      - 3000:3000
    networks:
      - ra-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMQ-RA
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - ra-network